import Head from 'next/head'
import Image from 'next/image'
import {useState, useEffect } from 'react'
import Movies from '../components/Movies';
import SearchBox from '../components/SearchBox';

export async function getStaticProps() {
  const url = 'http://www.omdbapi.com/?s=terminator&apikey=7ac48157&7ac48157';
  const res = await fetch(url);
  const data = await res.json();
  
  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { movies: data },
  }
}

export default function Home({movies}) {
  return (
    <div>
      <Head>
        <title>Movieselector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='mt-8'><h1>Movieselector</h1></div>
      <div>
        <SearchBox/>
      </div>
      <div>
        <Movies movies = {movies}/>
      </div>
    </div>
  )
}