import Head from 'next/head'
import Image from 'next/image'
import {useState, useEffect } from 'react'

function Movies({movies}) {
  return (
    <ul>
      {movies.Search.map((movie,index) => (
        <li>{movie.Title}</li>
      ))}
    </ul>
  );
}

export async function getStaticProps() {
  const url = 'http://www.omdbapi.com/?s=star wars&apikey=7ac48157&7ac48157';
  const res = await fetch(url);
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { movies: data },
  }
}

export default function Home({movies}) {
  return (
    <div>
      <Head>
        <title>Movieselector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello</h1>
      <Movies movies = {movies}/>
    </div>
  )
}
